# Specify TMS reconstruction values
# Read in by the general sim manager (TMS_Sim_Manager) for persistency

# Sim parameter constants
[Sim]
  [Sim.Readout]
    #  |----  readout time -----|------- deadtime ----{zombie time}]
    # All hits within this interval are combined into one
    ReadoutTime = 120.0 # ns
    # How long a channel is dead before it can read again
    Deadtime = 500.0 # ns, < 0 to turn off
    # Hits that happen in deadtime's zombie time get read as a new hit at the start of the next readout interval
    ZombieTime = -1.0 # ns, < 0 to turn off
    ReadoutNoise = 0.4 # in PE
    PedestalSubtractionThreshold = 3.0 # In PE
    
  [Sim.Optical]
    ShouldSimulatePoisson = true
    BirksConstant =  0.0905 # mm / MeV
    
    ShouldSimulateFiberLengths = true
    WSFAttenuationLength = 4.160 # m
    WSFLengthMultiplier = 1.8 # Light doesn't travel straight through the fiber
    WSFEndReflectionEff = 0.95 
    AdditionalFiberLength = -1.0 # m
    AdditionalFiberAttenuationLength = 4.160 # m
    AdditionalFiberCouplingEff = 0.9
    
    ReadoutCouplingEff = 1.0
    LightYield = 50.0 # PE per MeV
    
  [Sim.Noise]
    DarkNoiseRate = 2550.0 # hz
    DarkNoiseMinPE = 3.5 # pe
    
    
    
    
    

