# Specify TMS reconstruction values
# Read in by the general manager (TMS_Manager) for persistency

# Recon parameter constants
[Recon]
  # Minimum number of hits to consider reconstructing the event
  MinHits = 5

  # Track reco; Hough, AStar, DBSCAN
  TrackMethod = "Hough"
  #TrackMethod = "AStar"
  #TrackMethod = "DBSCAN"

  # Run clustering algorithm (DBSCAN) after track finding?
  Clustering = true
  #Clustering = false

  [Recon.DBSCAN]
    # The minimum points for the DBSCAN clustering algorithm
    MinPoints = 2
    # How far away can a bar/plane combination be to include in a cluster
    Epsilon = 2.5
    # Amount of neighbouring hits a hit needs to have for pre-clustering (DBSCAN)
    PreDBNeighbours = 9
    # Maximal distance to hits to count as neighbours for pre-clustering (DBSCAN)
    PreDBDistance = 2.5

  [Recon.Hough]
    # The highest number of Hough transforms we can run after each other
    MaxTrans = 10
    # Intercepts
    MinInter = -50.0E3
    MaxInter = 50.0E3
    # Slopes
    MinSlope = -5.0
    MaxSlope = 5.0
    # Number of Hough bins, resolution should be about 1cm
    #NSlope = 10000
    #NInter = 10000
    NSlope = 1000
    NInter = 1000
    # Minimum distance for Hough
    # What factor of hits of total do we need to cover to count a successful Hough line finding
    HitMult = 0.2
    # Minimum distance for a Hough track (prevents overfinding) -- in bars and plane
    # dist = sqrt(xplanes*xplanes + zplanes*zplanes)
    MinDist = 4.0
    # Do we run DBSCAN clustering before the Hough transform and then run Hough on each cluster?
    FirstCluster = false  #true
    # Do we merge adjacent tracks afterwards?
    MergeTracks = true
    # Do we run AStar afterwards on start and end points
    # To undo the greediness in the Hough line finding?
    RunAStarCleanup = true

  [Recon.Extrapolation]
    # Whether extrapolation should be performed or not
    Extrapolation = true
    # Maximal distance from start/end hit to first added hit by extrapolation
    ExtrapolateDist = 4
    # Maximal distance from first added hit (by extrapolation) to last added hit
    ExtrapolateLimit = 20
    # Distance in number of bars a hit can be away from the direction line at the end
    NumBarsEnd = 4
    # Distance in number of bars a hit can be away from the direction line at the start
    NumBarsStart = 2

  [Recon.TrackMatch3D]
    # How many plane layers can the ends/starts of the two simple tracks be away from each other?
    PlaneLimit = 2
    # How many bars can the ends/starts of the two simple tracks be away from each other?
    BarLimit = 12
    # How many ns can the ends/starts of the two simple tracks be away from each other?
    TimeLimit = 16  #30
    # How many ns can the ends/starts of a X simple track be away from U simple track?
    XTimeLimit = 40 #15 # (~10 ns time difference for 3.1m long bars both, plus a bit extra)
    # What is the 'anchor point' of the scintillator bars in y [mm]?
    YAnchor = -910.0
    # Tilt angle of scintillator planes for calculation of y (tan(90-angle))
    TiltAngle = 19.0811366877 #tan(90-3=87)
    # Y difference for expectation of reconstruction from UV and from X hit [mm]
    YDifference = 3000.0
    # Distance from start to calculate track direction for [Number of planes]. Track matching done in plane pairs -> do not set to 1
    DirectionDistance = 14

  [Recon.TrackSmoothing]
    UseTrackSmoothing = true
    TrackSmoothingStrategy = "simple"
    # This is the max y distance a track can travel in a UV detector
    # before we expect to see another transition point
    # Used to calculate the maximum slope you can hide in the UV Y position uncertainty
    MaxYDistanceBetweenUVTransitionPoints = 300.0 # mm
    # For a UV detector, this is the uncertainty in X
    # Numbers from TMS det review 2024-10-18
    UncertaintyGoodDirection = 18.0 # mm
    # For a UV detector, this is the default uncertainty in Y
    UncertaintyBadDirection = 340.0 # mm
    # In UV detector, transition point has better uncertainty
    # This is found using the FWHM of reco - true for transition points only
    UncertaintyForUVTransitionPoints = 120.0 # mm

  [Recon.AStar]
    #CostMetric = "Manhattan"
    CostMetric = "Euclidean"
    #CostMetric = "DetectorZ"
    #CostMetric = "DetectorNotZ"
    IsGreedy = false

  [Recon.Kalman]
    Run = true # Whether we run the Kalman filter or not
    Assumed_Charge = 0.5 # Assumed to be a muon , 0.1 is for the assumption of being a muon. -0.1 is for the assumption of being an anti-muon. 0.0 is for no magnetic field.

  [Recon.Stopping]
    nLastHits = 5 # The number of hits at the end of track to look at for stopping
    EnergyCut = 2.5 # The cut in MeV to see if a track has come to a stop or not
    
  [Recon.Time]
    RunTimeSlicer = true # Whether to run a time slicer
    TimeSlicerThresholdStart = 10.0 # The minimum window energy to start a slice
    TimeSlicerThresholdEnd = 5.0 # The window energy to end a slice
    SliceUnit = 1.0 # ns, the algorithm splits an array into TimeSlicerMaxTime/SliceUnit chunks. Each array represents 1 SliceUnit of time
    TimeSlicerEnergyWindowInUnits = 10 # units, so 10*1ns unit = 10ns window
    TimeSlicerMinimumSliceWidthInUnits = 19 # units, the minimum width of a slice in time
    TimeSlicerMaxTime = 10000.0 # ns, how far in time to search for slices
    RunSimpleTimeSlicer = false # Whether to run a simple time slicer which splits slices into X slices
    
  [Recon.Calibration]
    EnergyCalibration = 0.08856 # MeV / PE
    
[Fiducial]
  [Fiducial.TMS.Start]
    X = -3419.0 # mm  # TODO this is very preliminary
    Y = -2976.23 # mm # TODO this is very preliminary
    Z = 11134.0 # mm
  [Fiducial.TMS.End]
    X = 3419.0 # mm   # TODO this is very preliminary
    Y = 291.77 # mm   # TODO this is very preliminary
    Z = 18535.0 # mm
  [Fiducial.LAr.Start]
    X = -3478.48 # mm
    Y = -2166.71 # mm
    Z = 4179.24 # mm
  [Fiducial.LAr.End]
    X = 3478.48 # mm
    Y = 829.282 # mm
    Z = 9135.88 # mm
  [Fiducial.LAr]
    OuterShellThickness=300.0

# Options for processing and saving truth information
# LightWeight reduces run time signficantly because we only care about TMS objects (no LAr)
[Truth]
  LightWeight = false
  LArFiducialCut = 200.0 # mm

# Draw PDF of "event display". Slows down reco considerably
[Applications]
  DrawPDF = false
  MaximumNEvents = 100

# Variables that have to do with the geometry or location of the detector 
[Geometry]
  YBarMiddle = -1.35  #m
