# Specify TMS reconstruction values
# Read in by the general manager (TMS_Manager) for persistency

# Recon parameter constants
[Recon]
  # Minimum number of hits to consider reconstructing the event
  MinHits = 5

  # Track reco; Hough, AStar, DBSCAN
  TrackMethod = "Hough"
  #TrackMethod = "AStar"
  #TrackMethod = "DBSCAN"

  # Run clustering algorithm (DBSCAN) after track finding?
  Clustering = true
  #Clustering = false

  [Recon.DBSCAN]
    # The minimum points for the DBSCAN clustering algorithm
    MinPoints = 3
    # How far away can a bar/plane combination be to include in a cluster
    Epsilon = 2.5

  [Recon.Hough]
    # The highest number of transform we can run
    MaxTrans = 10
    # Intercepts
    MinInter = -50.0E3
    MaxInter = 50.0E3
    # Slopes
    MinSlope = -5.0
    MaxSlope = 5.0
    # Number of Hough bins, resolution should be about 1cm
    NSlope = 10000
    NInter = 10000
    # Minimum distance for Hough
    # What factor of hits of total do we need to cover to count a successful Hough line finding
    HitMult = 0.2
    # Minimum distance for a Hough track (prevents overfinding) -- in mm
    MinDist = 450.0
    # Do we run DBSCAN clustering before the Hough transform and then run Hough on each cluster?
    FirstCluster = false
    # Do we merge adjacent tracks afterwards?
    MergeTracks = true
    # Do we run AStar afterwards on start and end points
    # To undo the greediness in the Hough line finding?
    RunAStarCleanup = true

  [Recon.AStar]
    #CostMetric = "Manhattan"
    #CostMetric = "Euclidean"
    CostMetric = "DetectorZ"
    #CostMetric = "DetectorNotZ"
    IsGreedy = false

# Options for processing and saving truth information
# LightWeight reduces run time signficantly because we only care about TMS objects (no LAr)
[Truth]
  LightWeight = false

# Draw PDF of "event display". Slows down reco considerably
[Applications]
  DrawPDF = false
