# Specify TMS reconstruction values
# Read in by the general manager (TMS_Manager) for persistency

# Recon parameter constants
[Recon]
  # Minimum number of hits to consider reconstructing the event
  MinHits = 5

  # Track reco; Hough, AStar, DBSCAN
  TrackMethod = "Hough"
  #TrackMethod = "AStar"
  #TrackMethod = "DBSCAN"

  # Run clustering algorithm (DBSCAN) after track finding?
  Clustering = true
  #Clustering = false

  [Recon.DBSCAN]
    # The minimum points for the DBSCAN clustering algorithm
    MinPoints = 2
    # How far away can a bar/plane combination be to include in a cluster
    Epsilon = 2.5

  [Recon.Hough]
    # The highest number of Hough transforms we can run after each other
    MaxTrans = 10
    # Intercepts
    MinInter = -50.0E3
    MaxInter = 50.0E3
    # Slopes
    MinSlope = -5.0
    MaxSlope = 5.0
    # Number of Hough bins, resolution should be about 1cm
    #NSlope = 10000
    #NInter = 10000
    NSlope = 1000
    NInter = 1000
    # Minimum distance for Hough
    # What factor of hits of total do we need to cover to count a successful Hough line finding
    HitMult = 0.2
    # Minimum distance for a Hough track (prevents overfinding) -- in bars and plane
    # dist = sqrt(xplanes*xplanes + zplanes*zplanes)
    MinDist = 4.0
    # Do we run DBSCAN clustering before the Hough transform and then run Hough on each cluster?
    FirstCluster = false
    # Do we merge adjacent tracks afterwards?
    MergeTracks = true
    # Do we run AStar afterwards on start and end points
    # To undo the greediness in the Hough line finding?
    RunAStarCleanup = true

  [Recon.Extrapolation]
    # Whether extrapolation should be performed or not
    Extrapolation = true
    # Maximal distance from start/end hit to first added hit by extrapolation
    ExtrapolateDist = 4
    # Maximal distance from first added hit (by extrapolation) to last added hit
    ExtrapolateLimit = 20
    # Distance in number of bars a hit can be away from the direction line at the end
    NumBarsEnd = 4
    # Distance in number of bars a hit can be away from the direction line at the start
    NumBarsStart = 2

  [Recon.TrackMatch3D]
    # How many plane layers can the ends/starts of the two simple tracks be away from each other?
    PlaneLimit = 3
    # How many bars can the ends/starts of the two simple tracks be away from each other?
    BarLimit = 12
    # How many ns can the ends/starts of the two simple tracks be away from each other?
    TimeLimit = 30
    # How many ns can the ends/starts of a X simple track be away from U simple track?
    XTimeLimit = 15 # (~10 ns time difference for 3.1m long bars both, plus a bit extra)
    # What is the 'anchor point' of the scintillator bars in y [mm]?
    YAnchor = -910.0
    # Tilt angle of scintillator planes for calculation of y (tan(90-angle))
    TiltAngle = 19.0811366877 #tan(90-3=87)
    # Y difference for expectation of reconstruction from UV and from X hit [mm]
    YDifference = 3000.0
    # Distance from start to calculate track direction for [Number of planes]. Track matching done in plane pairs -> do not set to 1
    DirectionDistance = 10

  [Recon.AStar]
    #CostMetric = "Manhattan"
    CostMetric = "Euclidean"
    #CostMetric = "DetectorZ"
    #CostMetric = "DetectorNotZ"
    IsGreedy = false

  [Recon.Stopping]
    nLastHits = 5 # The number of hits at the end of track to look at for stopping
    EnergyCut = 2.5 # The cut in MeV to see if a track has come to a stop or not
    
  [Recon.Time]
    RunTimeSlicer = true # Whether to run a time slicer
    TimeSlicerThresholdStart = 10.0 # The minimum window energy to start a slice
    TimeSlicerThresholdEnd = 5.0 # The window energy to end a slice
    SliceUnit = 1.0 # ns, the algorithm splits an array into TimeSlicerMaxTime/SliceUnit chunks. Each array represents 1 SliceUnit of time
    TimeSlicerEnergyWindowInUnits = 10 # units, so 10*1ns unit = 10ns window
    TimeSlicerMinimumSliceWidthInUnits = 19 # units, the minimum width of a slice in time
    TimeSlicerMaxTime = 10000.0 # ns, how far in time to search for slices
    RunSimpleTimeSlicer = false # Whether to run a simple time slicer which splits slices into X slices
    
  [Recon.Calibration]
    EnergyCalibration = 0.08856 # MeV / PE


# Options for processing and saving truth information
# LightWeight reduces run time signficantly because we only care about TMS objects (no LAr)
[Truth]
  LightWeight = false

# Draw PDF of "event display". Slows down reco considerably
[Applications]
  DrawPDF = false
  MaximumNEvents = 10

# Variables that have to do with the geometry or location of the detector 
[Geometry]
  YBarMiddle = -1.35  #m
