name: C/C++ CI

on:
  push:
    branches: [ "main", "Liam-CI-test" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone TOML
      run: git clone https://github.com/ToruNiina/toml11
    - uses: actions/checkout@v3
    - name: make
      run: make
